[package]
edition = "2018"
name = "xtask"
version = "0.0.0"
publish = false
license = "MIT"

[dependencies]
anyhow = "1"
# xshell = "0.1"
# xflags = "0.2.1"
# Avoid adding more dependencies to this crate
