[package]
name = "rome_js_syntax"
version = "0.0.0"
description = "SyntaxKind and common rowan definitions for rome_js_parser"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rome_rowan = { path = "../rome_rowan" }
serde = { version = "1.0.136", features = ["derive"], optional = true }
schemars = { version = "0.8.10", optional = true }

[dev-dependencies]
rome_js_factory = { path = "../rome_js_factory" }

[features]
serde = ["dep:serde", "schemars", "rome_rowan/serde"]
