name: Auto-publish
on:
  push:
    branches:
    - main
    paths:
    - 'package.json'

jobs:
  check:
    name: Check version update
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      type: ${{ steps.check.outputs.type }}
    steps:
      - uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true

  publish:
    name: Publish
    needs: check
    if: needs.check.outputs.changed == 'true'
    environment: nightly
    runs-on: ubuntu-latest
    steps:
      - name: Version update detected
        run: 'echo "Version change found! New version: ${{ needs.check.outputs.version }} (${{ needs.check.outputs.type }})"'

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: Build Release
        run: ./rome run scripts/build-release dist

      - name: Check if prerelease
        id: check-prelease
        if: needs.check.outputs.type == 'prerelease' || needs.check.outputs.type == 'prepatch' || needs.check.outputs.type == 'premajor' || needs.check.outputs.type == 'preminor'
        run: echo "::set-output name=prerelease::true"

      - name: Publish to npm as latest
        if: steps.check-prelease.outputs.prelease != 'true'
        run: npm publish dist --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm as prerelease
        if: steps.check-prelease.outputs.prelease = 'true'
        run: npm publish dist --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update latest branch
        if: steps.check-prelease.outputs.prelease != 'true'
        uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: latest
          force: 1
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release and tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check.outputs.version }}
          release_name: v${{ needs.check.outputs.version }}
          draft: false
          prerelease: false
