# Parser benchmark, compares main and PR branch with Criterion.
# Comment with text containing `!bench`, a new result will be commented at the bottom of this PR.

name: Parser Benchmark

on:
  issue_comment:
    types: [created]

env:
  RUST_LOG: info

jobs:
  bench:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!bench_parser')
    uses: ./.github/workflows/xtask_bench.yaml
    with:
      name: Parser
      command: bench_parser
    secrets: inherit
