name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: TBD
        run: echo "TBD"

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: TBD
        run: echo "TBD"

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: TBD
        run: echo "TBD"
