name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  typescript:
    runs-on: ubuntu-latest
    name: TypeScript Check

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run TypeScript
        run: node ./node_modules/.bin/tsc --noEmit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [typescript]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run Rome test
        run: node scripts/dev-rome test --freeze-snapshots

  tests:
    name: Tests
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run Rome lint
        run: node scripts/dev-rome lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Build release
        run: node scripts/build-release dist

      - name: Create tarball
        run: tar -C dist -czvf dist.tar.gz .

      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: package.tgz
          path: dist.tar.gz
