name: Deploy Playground

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: # Only deploy when changes are made to the crates or playground code
      - 'crates/**'
      - 'website/playground/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: netlify-playground
    name: Deploy Playground
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Build WASM module for the web
        run: wasm-pack build --out-dir ../../npm/wasm-web --target web --release --scope rometools crates/rome_wasm
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
          run_install: |
            args: [--prefix website/playground]
      - run: pnpm --prefix website/playground build:js
      - name: Publish
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'website/playground/dist'